apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup-diff
spec:
  schedule: "0 9 * * 1-6"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ .Release.Name }}-backup-diff
          labels:
            app: {{ .Release.Name }}
            component: backup-diff
        spec:
          serviceAccount: {{ .Release.Name }}-backup
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: backup
              image: {{ .Values.kubectl.image }}
              imagePullPolicy: Always
              command:
                - "sh"
                - "-e"
                - "-c"
                - |
                  kubectl --namespace {{ .Release.Namespace }} get pods --selector=app={{ .Release.Name }},component=database
                  POD=$(kubectl --namespace {{ .Release.Namespace }} get pods --selector=app={{ .Release.Name }},component=database -o json | jq -r '.items[0].metadata.name')
                  kubectl --namespace {{ .Release.Namespace }} exec $POD -c postgresql -- \
                    /usr/bin/pgbackrest \
                    --type=diff \
                    --start-fast \
                    --stop-auto \
                    backup
              env:
                - name: "TZ"
                  value: "{{ .Values.timezone }}"
              {{- with .Values.kubectl.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
