apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: database
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 26
        runAsGroup: 26
        fsGroup: 26
      initContainers:
        - name: chown
          image: docker.io/library/busybox:1.33.1
          imagePullPolicy: Always
          command:
            - "sh"
            - "-e"
            - "-c"
            - |
              chown -PRc 26:26 /var/lib/pgsql/13/data
              chmod -Rc og= /var/lib/pgsql/13/data
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/13/data
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          imagePullPolicy: Always
          env:
            - name: "TZ"
              value: "{{ .Values.timezone }}"
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-postgresql
            - secretRef:
                name: {{ .Release.Name }}-pgbackrest
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: run
              mountPath: /run
            - name: tmp
              mountPath: /tmp
            - name: varrunpostgresql
              mountPath: /var/run/postgresql
            - name: data
              mountPath: /var/lib/pgsql/13/data
          {{- with .Values.postgresql.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: varrunpostgresql
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
