---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name}}-library
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.storageClassName }}
