apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: {{ .Release.Name }}
    component: database
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
