timezone: "America/Chicago"

postgresql:
  image: "ghcr.io/jcollie/postgresql:latest"
  password: "secret"
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 1Gi
    # requests:
    #   cpu: 1000m
    #   memory: 1Gi

pgbackrest:
  retention:
    length: 14
    type: "time"
  encryption:
    password: ""
  repo:
    # s3 or azure
    type: "s3"
    prefix: "s/"
    s3:
      # name of the S3 bucket to use
      bucket: ""
      # url of the S3 endpoint
      endpoint: ""
      # S3 key
      key: ""
      # S3 region
      region: ""
      # S3 secret
      secret: ""
    azure:
      # Azure account
      account: ""
      # Azure container
      container: ""
      # Azure key
      key: ""

kubectl:
  image: "ghcr.io/jcollie/kubectl:latest"
  resources: {}
    # requests:
    #   cpu: 125m
    #   memory: 128Mi
    # limits:
    #   cpu: 125m
    #   memory: 128Mi

storageClassName: ""
imagePullSecrets: []
