timezone: "America/Chicago"

postgresql:
  image: ""
  password: "secret"

pgbackrest:
  retention:
    length: 14
    type: "time"
  encryption:
    password: ""
  repo:
    # s3 or azure
    type: "s3"
    path: ""
    s3:
      # name of the S3 bucket to use
      bucket: ""
      # url of the S3 endpoint
      endpoint: ""
      # S3 key
      key: ""
      # S3 region
      region: ""
      # S3 secret
      secret: ""
    azure:
      # Azure account
      account: ""
      # Azure container
      container: ""
      # Azure key
      key: ""

kubectl:
  image: ""

storageClassName: ""
imagePullSecrets: []
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1000m
  #   memory: 1Gi
  # requests:
  #   cpu: 1000m
  #   memory: 1Gi
