apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-backup
roleRef:
  name: {{ .Release.Name }}-backup
  apiGroup: rbac.authorization.k8s.io
  kind: Role
subjects:
  - name: {{ .Release.Name }}-backup
    kind: ServiceAccount
