---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-postgresql
stringData:
  POSTGRES_INITDB_ARGS: "--data-checksums"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.password }}"
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-pgbackrest
stringData:
  PGBACKREST_LOG_LEVEL_CONSOLE: "info"
  PGBACKREST_LOG_LEVEL_FILE: "off"
  PGBACKREST_LOG_LEVEL_STDERR: "off"
  PGBACKREST_PG1_PATH: "/var/lib/postgresql/data"
  PGBACKREST_REPO1_CIPHER_PASS: "{{ .Values.pgbackrest.encryption.password }}"
  PGBACKREST_REPO1_CIPHER_TYPE: "aes-256-cbc"
  PGBACKREST_REPO1_PATH: "{{ .Values.pgbackrest.repo.path }}"
  {{- if eq .Values.pgbackrest.repo.type "s3" }}
  PGBACKREST_REPO1_S3_BUCKET: "{{ .Values.pgbackrest.repo.s3.bucket }}"
  PGBACKREST_REPO1_S3_ENDPOINT: "{{ .Values.pgbackrest.repo.s3.bucket }}"
  PGBACKREST_REPO1_S3_KEY: "{{ .Values.pgbackrest.repo.s3.bucket }}"
  PGBACKREST_REPO1_S3_KEY_SECRET: "{{ .Values.pgbackrest.repo.s3.bucket }}"
  PGBACKREST_REPO1_S3_REGION: "{{ .Values.pgbackrest.repo.s3.bucket }}"
  PGBACKREST_REPO1_TYPE: "s3"
  {{ end -}}
  {{- if eq .Values.pgbackrest.repo.type "azure" }}
  PGBACKREST_REPO1_AZURE_ACCOUNT: "{{ .Values.pgbackrest.repo.azure.account }}"
  PGBACKREST_REPO1_AZURE_CONTAINER: "{{ .Values.pgbackrest.repo.azure.container }}"
  PGBACKREST_REPO1_AZURE_KEY: "{{ .Values.pgbackrest.repo.s3.bucket }}"
  PGBACKREST_REPO1_TYPE: "azure"
  {{ end -}}
  PGBACKREST_RETENTION_FULL: "{{ .Values.pgbackrest.retention.length }}"
  PGBACKREST_RETENTION_FULL_TYPE: "{{ .Values.pgbackrest.retention.type }}"
  PGBACKREST_STANZA: "{{ .Release.Name }}"
